debug: true
smsEnabled: true
rpc:
    listen: "0.0.0.0:1986"
web: 
    addrs: 
      - "127.0.0.1:1985"
    timeout: 300 
    interval: 60 #get strategy interval
smtp: 
    enabled: true
    addr: "smtp.qq.com:25"
    username: "2727250655@qq.com"
    password: "lcwdsazocsvbdecb"
    from: "2727250655@qq.com"
wechat:
    enabled: false
    toparty: "@all"     #需要发送指定人请使用"@all"
    agentid: 1000008
    corpid: ""
    corpsecret: ""
worker: 
    sms: 10  #send sms concurrency
    mail: 50 #send mail concurrency
    wechat: 50  #send wechat concurrency
# remain: 30
